#! /bin/bash

# This script is designed to find hosts with MySQL installed

# This is just a local scan that I tried on the virtual machine
nmap -sT <targetIP/targetIPLastOctet> -p <portNumber> >/dev/null -oG MySQLscan

cat MySQLscan | grep open > MySQLscan2

cat MySQLscan2

